# Generated by Django 5.0.14 on 2025-12-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hostel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hostelallocation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hostelfee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={},
        ),
        migrations.RenameIndex(
            model_name='bed',
            new_name='bed_room_id_7d2493_idx',
            old_name='bed_room_id_status_647179_idx',
        ),
        migrations.RenameIndex(
            model_name='hostel',
            new_name='hostel_college_ce293c_idx',
            old_name='hostel_college_ba4ba5_idx',
        ),
        migrations.RenameIndex(
            model_name='hostelallocation',
            new_name='hostel_allo_student_83de25_idx',
            old_name='hostel_all_student_540847_idx',
        ),
        migrations.RenameIndex(
            model_name='hostelfee',
            new_name='hostel_fee_allocat_b77b4a_idx',
            old_name='hostel_fee_allocati_3a1bd7_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='room_hostel__f1f8a0_idx',
            old_name='room_hostel_room_n_22baa8_idx',
        ),
        migrations.RenameIndex(
            model_name='roomtype',
            new_name='room_type_hostel__90c5e8_idx',
            old_name='room_type_hostel_i_757e24_idx',
        ),
    ]
