# Generated by Django 5.2.9
import uuid
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique user identifier (UUID)', primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, help_text='Unique username for authentication', max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='User email address', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('first_name', models.CharField(help_text='First name', max_length=100)),
                ('last_name', models.CharField(help_text='Last name', max_length=100)),
                ('middle_name', models.CharField(blank=True, help_text='Middle name', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('avatar', models.ImageField(blank=True, help_text='User avatar image', null=True, upload_to='avatars/')),
                ('user_type', models.CharField(choices=[('super_admin', 'Super Admin'), ('college_admin', 'College Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('staff', 'Support Staff')], db_index=True, default='student', help_text='User role/type in the system', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this user should be treated as active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin site')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if the email/phone is verified')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True)),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='Count of consecutive failed login attempts')),
                ('lockout_until', models.DateTimeField(blank=True, help_text='Account locked until this time', null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the user registered')),
                ('last_password_change', models.DateTimeField(blank=True, help_text='Timestamp of last password change', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='user_usernam_b79065_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='user_user_ty_088d91_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='user_is_acti_7f3bc2_idx'),
        ),
    ]
