# Generated by Django 5.2.9 to add college-scoped models after the custom User exists.
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='users',
                help_text='Primary college affiliation (null for super admins)',
                to='core.college',
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['college'], name='user_college_519591_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['college', 'user_type'], name='user_college_9e4e6b_idx'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('code', models.CharField(help_text="Department code (e.g., 'CS', 'ME')", max_length=20)),
                ('name', models.CharField(help_text='Department name', max_length=200)),
                ('short_name', models.CharField(blank=True, help_text='Abbreviated name', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Department description', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Display order in UI')),
                ('college', models.ForeignKey(help_text='Owning college', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('hod', models.ForeignKey(blank=True, help_text='Head of Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_as_hod', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('name', models.CharField(help_text="Role name (e.g., 'HOD', 'Class Coordinator')", max_length=100)),
                ('code', models.CharField(help_text='Unique role code', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Role description', null=True)),
                ('permissions', models.JSONField(default=dict, help_text='Permission set for this role (module-level access)')),
                ('display_order', models.IntegerField(default=0, help_text='Display order in UI')),
                ('college', models.ForeignKey(help_text='College this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('address_line1', models.CharField(blank=True, help_text='Address line 1', max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, help_text='Address line 2', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10, null=True)),
                ('country', models.CharField(default='India', help_text='Country', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact person name', max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone', max_length=20, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, help_text='Relationship to emergency contact', max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, help_text="Blood group (e.g., 'A+', 'O-')", max_length=5, null=True)),
                ('nationality', models.CharField(default='Indian', help_text='Nationality', max_length=100)),
                ('religion', models.CharField(blank=True, help_text='Religion', max_length=50, null=True)),
                ('caste', models.CharField(blank=True, help_text='Caste category', max_length=50, null=True)),
                ('profile_data', models.JSONField(default=dict, help_text='Additional profile data specific to user type')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('website_url', models.URLField(blank=True, help_text='Personal website URL', null=True)),
                ('bio', models.TextField(blank=True, help_text='User biography', null=True)),
                ('college', models.ForeignKey(help_text='Associated college', on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department affiliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='accounts.department')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the role was assigned')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Role expiration date (null = no expiration)', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who made this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(help_text='Associated college', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role assigned to the user', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User assigned to the role', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'db_table': 'user_role',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['college'], name='department_college_22b6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='department_code_c994f8_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='department_is_acti_8ce068_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('college', 'code'), name='unique_college_department_code'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['college'], name='role_college_183e37_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='role_code_df16be_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active'], name='role_is_acti_d578e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('college', 'code'), name='unique_college_role_code'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['college'], name='user_profil_college_48631b_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='user_profil_user_id_4f95f8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['department'], name='user_profil_departm_81761c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['college'], name='user_role_college_ee2b00_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user'], name='user_role_user_id_d8192c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='user_role_role_id_8c260c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['college', 'user'], name='user_role_college_7897cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('college', 'user', 'role'), name='unique_college_user_role'),
        ),
    ]
