# Generated by Django 5.2.9 on 2025-12-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(db_index=True, default=False, help_text='Superadmin has access to all colleges and all permissions'),
        ),
    ]
