# Generated by Django 5.2.9 on 2026-01-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('college_admin', 'College Admin'), ('central_manager', 'Central Store Manager'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('staff', 'Support Staff'), ('store_manager', 'Store Manager')], db_index=True, default='student', help_text='User role/type in the system', max_length=20),
        ),
    ]
