# Generated by Django 5.2.9 on 2026-01-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_organizational_position',
            field=models.BooleanField(default=True, help_text='Whether this is an organizational position'),
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.IntegerField(default=0, help_text='Hierarchy level (0=top, increases downward)'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent role in organizational hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.department'),
        ),
    ]
