# Generated by Django 5.0.14 on 2025-12-20 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('code', models.CharField(help_text='Category code', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_category',
            },
        ),
        migrations.CreateModel(
            name='StoreCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Credit amount', max_digits=10)),
                ('transaction_type', models.CharField(help_text='Type (credit/debit)', max_length=20)),
                ('date', models.DateField(help_text='Date')),
                ('reference_type', models.CharField(blank=True, help_text='Reference type', max_length=50, null=True)),
                ('reference_id', models.IntegerField(blank=True, help_text='Reference ID', null=True)),
                ('reason', models.TextField(help_text='Reason')),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Balance after transaction', max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='store_credits', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_credit',
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('name', models.CharField(help_text='Item name', max_length=200)),
                ('code', models.CharField(help_text='Item code', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('unit', models.CharField(help_text='Unit (piece/kg/ltr)', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Stock quantity')),
                ('min_stock_level', models.IntegerField(default=10, help_text='Minimum stock alert threshold')),
                ('barcode', models.CharField(blank=True, help_text='Barcode', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, help_text='Item image', null=True, upload_to='store_items/')),
                ('category', models.ForeignKey(help_text='Category', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.storecategory')),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_item',
            },
        ),
        migrations.CreateModel(
            name='StoreSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('sale_date', models.DateField(help_text='Sale date')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount', max_digits=10)),
                ('payment_method', models.CharField(help_text='Payment method', max_length=20)),
                ('payment_status', models.CharField(default='paid', help_text='Payment status', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Remarks', null=True)),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='store_sales', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sold_by', models.ForeignKey(blank=True, help_text='Sold by user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_sales_made', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, help_text='Student buyer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_sales', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher buyer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_sales', to='teachers.teacher')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_sale',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('quantity', models.IntegerField(help_text='Quantity sold')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price', max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='Item', on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='store.storeitem')),
                ('sale', models.ForeignKey(help_text='Sale', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.storesale')),
            ],
            options={
                'db_table': 'sale_item',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('name', models.CharField(help_text='Vendor name', max_length=200)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=254, null=True)),
                ('phone', models.CharField(help_text='Phone', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Address', null=True)),
                ('gstin', models.CharField(blank=True, help_text='GSTIN', max_length=15, null=True)),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.CreateModel(
            name='StockReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('quantity', models.IntegerField(help_text='Quantity received')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount', max_digits=10)),
                ('receive_date', models.DateField(help_text='Receive date')),
                ('invoice_number', models.CharField(blank=True, help_text='Invoice number', max_length=50, null=True)),
                ('invoice_file', models.FileField(blank=True, help_text='Invoice file', null=True, upload_to='store_invoices/')),
                ('remarks', models.TextField(blank=True, help_text='Remarks', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='Item', on_delete=django.db.models.deletion.CASCADE, related_name='stock_receipts', to='store.storeitem')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_receipts', to='store.vendor')),
            ],
            options={
                'db_table': 'stock_receive',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('job_name', models.CharField(help_text='Job name', max_length=200)),
                ('file', models.FileField(blank=True, help_text='File to print', null=True, upload_to='print_jobs/')),
                ('pages', models.IntegerField(help_text='Number of pages')),
                ('copies', models.IntegerField(default=1, help_text='Number of copies')),
                ('paper_size', models.CharField(default='A4', help_text='Paper size', max_length=20)),
                ('color_type', models.CharField(default='bw', help_text='Color type (bw/color)', max_length=20)),
                ('per_page_cost', models.DecimalField(decimal_places=2, help_text='Per page cost', max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount', max_digits=10)),
                ('submission_date', models.DateField(help_text='Submission date')),
                ('completion_date', models.DateField(blank=True, help_text='Completion date', null=True)),
                ('status', models.CharField(default='pending', help_text='Status', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Remarks', null=True)),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Teacher', on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='teachers.teacher')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'print_job',
                'indexes': [models.Index(fields=['college', 'teacher', 'submission_date', 'status'], name='print_job_college_c45b1f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='storecategory',
            index=models.Index(fields=['college', 'code'], name='store_categ_college_c31bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='storecategory',
            index=models.Index(fields=['college', 'is_active'], name='store_categ_college_869158_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storecategory',
            unique_together={('college', 'code')},
        ),
        migrations.AddIndex(
            model_name='storecredit',
            index=models.Index(fields=['student', 'date'], name='store_credi_student_a04f86_idx'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['college', 'category'], name='store_item_college_2c69aa_idx'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['college', 'code'], name='store_item_college_a46b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['barcode'], name='store_item_barcode_38064f_idx'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['is_active'], name='store_item_is_acti_53d328_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeitem',
            unique_together={('college', 'code')},
        ),
        migrations.AddIndex(
            model_name='storesale',
            index=models.Index(fields=['college', 'student', 'teacher', 'sale_date'], name='store_sale_college_11b15a_idx'),
        ),
        migrations.AddIndex(
            model_name='storesale',
            index=models.Index(fields=['payment_status'], name='store_sale_payment_1a50c3_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'item'], name='sale_item_sale_id_e4fa17_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['college'], name='vendor_college_9ba0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active'], name='vendor_is_acti_aca0de_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreceive',
            index=models.Index(fields=['item', 'vendor', 'receive_date'], name='stock_recei_item_id_e39f69_idx'),
        ),
    ]
