# Generated by Django 5.2.9 on 2026-01-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_create_store_manager_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeindent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_college_approval', 'Pending College Admin Approval'), ('college_approved', 'College Admin Approved'), ('pending_super_admin', 'Pending Super Admin Approval'), ('super_admin_approved', 'Super Admin Approved'), ('approved', 'Approved'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('rejected_by_college', 'Rejected by College Admin'), ('rejected_by_super_admin', 'Rejected by Super Admin'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
