# Generated by Django 5.2.9 on 2026-01-15 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_collegestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='item_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='ordered_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_items', to='store.purchaseorderitem'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='received_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='central_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='store.centralstore'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='store.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='store.suppliermaster'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='requirement_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='store.requirementitem'),
        ),
    ]
