# Generated by Django 5.2.9 on 2026-01-13 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dynamicrole_hierarchypermission_hierarchyuserrole_and_more'),
        ('store', '0007_collegestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecategory',
            name='college',
            field=models.ForeignKey(blank=True, help_text='College reference (null for central items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='core.college'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='college',
            field=models.ForeignKey(blank=True, help_text='College reference (null for central items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='core.college'),
        ),
    ]
