# Generated by Django 5.2.9 on 2026-01-15 06:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('fees', 'Fees'), ('hr', 'HR'), ('store', 'Store'), ('other', 'Other')], max_length=50)),
                ('month', models.DateField(help_text='First day of the month')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transaction_count', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_app_expense',
                'ordering': ['-month', 'app_name'],
                'indexes': [models.Index(fields=['app_name', 'month'], name='finance_app_app_nam_6a42e2_idx'), models.Index(fields=['month'], name='finance_app_month_82278f_idx')],
                'unique_together': {('app_name', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AppIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('fees', 'Fees'), ('library', 'Library'), ('hostel', 'Hostel'), ('store', 'Store')], max_length=50)),
                ('month', models.DateField(help_text='First day of the month')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transaction_count', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_app_income',
                'ordering': ['-month', 'app_name'],
                'indexes': [models.Index(fields=['app_name', 'month'], name='finance_app_app_nam_7c5a68_idx'), models.Index(fields=['month'], name='finance_app_month_ede001_idx')],
                'unique_together': {('app_name', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AppTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('fees', 'Fees'), ('library', 'Library'), ('hostel', 'Hostel'), ('hr', 'HR'), ('store', 'Store'), ('other', 'Other')], max_length=50)),
                ('month', models.DateField(help_text='First day of the month')),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_app_total',
                'ordering': ['-month', 'app_name'],
                'indexes': [models.Index(fields=['app_name', 'month'], name='finance_app_app_nam_b5d96f_idx'), models.Index(fields=['month'], name='finance_app_month_367a46_idx')],
                'unique_together': {('app_name', 'month')},
            },
        ),
        migrations.CreateModel(
            name='FinanceTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month', unique=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_total',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='finance_tot_month_64c172_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('fees', 'Fees'), ('library', 'Library'), ('hostel', 'Hostel'), ('hr', 'HR'), ('store', 'Store'), ('other', 'Other')], max_length=50)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID from source app', null=True)),
                ('reference_model', models.CharField(blank=True, help_text='Source model name', max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_transaction',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['app', 'type'], name='finance_tra_app_267f82_idx'), models.Index(fields=['date'], name='finance_tra_date_f21d66_idx'), models.Index(fields=['reference_model', 'reference_id'], name='finance_tra_referen_27d956_idx')],
            },
        ),
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('supplies', 'Supplies'), ('marketing', 'Marketing'), ('travel', 'Travel'), ('miscellaneous', 'Miscellaneous')], max_length=50)),
                ('date', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='finance/receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_other_expense',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='finance_oth_date_2be222_idx'), models.Index(fields=['category'], name='finance_oth_categor_ec4f4d_idx'), models.Index(fields=['created_at'], name='finance_oth_created_22a9ad_idx')],
            },
        ),
    ]
