# Generated by Django 5.2.9 on 2026-01-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('online', 'Online Payment'), ('cheque', 'Cheque'), ('upi', 'UPI')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('online', 'Online Payment'), ('cheque', 'Cheque'), ('upi', 'UPI')], default='cash', max_length=20),
        ),
    ]
