"""
Reports models for templates and generated reports.
"""
from django.conf import settings
from django.db import models

from apps.core.models import CollegeScopedModel, AuditModel, College


class ReportTemplate(CollegeScopedModel):
    college = models.ForeignKey(
        College,
        on_delete=models.CASCADE,
        related_name='report_templates',
        help_text="College reference"
    )
    name = models.CharField(max_length=200, help_text="Template name")
    report_type = models.CharField(max_length=50, help_text="Report type")
    description = models.TextField(null=True, blank=True, help_text="Description")
    query_params = models.JSONField(null=True, blank=True, help_text="Query parameters")

    class Meta:
        db_table = 'report_template'
        indexes = [
            models.Index(fields=['college', 'report_type']),
            models.Index(fields=['is_active']),
        ]

    def __str__(self):
        return f"{self.name} ({self.report_type})"


class GeneratedReport(AuditModel):
    template = models.ForeignKey(
        ReportTemplate,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='generated_reports',
        help_text="Template"
    )
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='generated_reports',
        help_text="Generated by"
    )
    file = models.FileField(upload_to='reports/generated/', null=True, blank=True, help_text="Report file")
    filters = models.JSONField(null=True, blank=True, help_text="Applied filters")
    generation_date = models.DateField(help_text="Generation date")

    class Meta:
        db_table = 'generated_report'
        indexes = [
            models.Index(fields=['template', 'generated_by', 'generation_date']),
        ]

    def __str__(self):
        return f"Generated report {self.id} on {self.generation_date}"


class SavedReport(CollegeScopedModel):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='saved_reports',
        help_text="User"
    )
    college = models.ForeignKey(
        College,
        on_delete=models.CASCADE,
        related_name='saved_reports',
        help_text="College reference"
    )
    name = models.CharField(max_length=200, help_text="Report name")
    report_type = models.CharField(max_length=50, help_text="Report type")
    filters = models.JSONField(help_text="Saved filters")

    class Meta:
        db_table = 'saved_report'
        indexes = [
            models.Index(fields=['user', 'college', 'report_type']),
            models.Index(fields=['is_active']),
        ]

    def __str__(self):
        return f"{self.name} ({self.report_type})"
