"""
Signals for Reports app.
Sends notification placeholder when a report is generated.
"""
from django.db.models.signals import post_save
from django.dispatch import receiver

from .models import GeneratedReport


@receiver(post_save, sender=GeneratedReport)
def generated_report_post_save(sender, instance, created, **kwargs):
    if created:
        print(f"[Reports] Report generated by {instance.generated_by} on {instance.generation_date}.")
