# Generated by Django 5.2.9 on 2025-12-04 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('code', models.CharField(db_index=True, help_text='Unique college code', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name of the college', max_length=200)),
                ('short_name', models.CharField(help_text='Abbreviated name', max_length=50)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('website', models.URLField(blank=True, help_text='College website URL', null=True)),
                ('address_line1', models.CharField(help_text='Address line 1', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Address line 2', max_length=255, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('pincode', models.CharField(help_text='Postal/ZIP code', max_length=10)),
                ('country', models.CharField(default='India', help_text='Country', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='College logo (stored in S3)', null=True, upload_to='college_logos/')),
                ('established_date', models.DateField(blank=True, help_text='Date of establishment', null=True)),
                ('affiliation_number', models.CharField(blank=True, help_text='Official affiliation identifier', max_length=100, null=True)),
                ('primary_color', models.CharField(default='#1976d2', help_text='Primary brand color (hex format)', max_length=7)),
                ('secondary_color', models.CharField(default='#dc004e', help_text='Secondary brand color (hex format)', max_length=7)),
                ('settings', models.JSONField(blank=True, help_text='College-specific settings (academic, fees, notifications, theme)', null=True)),
                ('is_main', models.BooleanField(default=False, help_text='Indicates if this is the main university')),
                ('display_order', models.IntegerField(default=0, help_text='Display order in UI')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'db_table': 'college',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('download', 'Download'), ('upload', 'Upload'), ('export', 'Export'), ('import', 'Import')], help_text='Type of action performed', max_length=20)),
                ('model_name', models.CharField(help_text='Name of the model/entity affected', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the affected record', max_length=100, null=True)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('metadata', models.JSONField(blank=True, help_text='Additional data (changes, request info, etc.)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(help_text='Associated college', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.college')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('year', models.CharField(help_text="Academic year label (e.g., '2025-2026')", max_length=20)),
                ('start_date', models.DateField(help_text='Academic year start date')),
                ('end_date', models.DateField(help_text='Academic year end date')),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='Indicates if this is the current academic year')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(help_text='Owning college', on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.college')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'academic_year',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('name', models.CharField(help_text='Session name', max_length=100)),
                ('semester', models.IntegerField(help_text='Semester number (1-8)')),
                ('start_date', models.DateField(help_text='Session start date')),
                ('end_date', models.DateField(help_text='Session end date')),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='Indicates if this is the current session')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('academic_year', models.ForeignKey(help_text='Associated academic year', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.academicyear')),
                ('college', models.ForeignKey(help_text='Associated college', on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='core.college')),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'db_table': 'academic_session',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('name', models.CharField(help_text='Name of the holiday', max_length=200)),
                ('date', models.DateField(db_index=True, help_text='Holiday date')),
                ('holiday_type', models.CharField(choices=[('national', 'National Holiday'), ('festival', 'Festival'), ('college', 'College Holiday'), ('exam', 'Exam Holiday')], help_text='Type of holiday', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the holiday', null=True)),
                ('college', models.ForeignKey(help_text='Associated college', on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holiday',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('sms_enabled', models.BooleanField(default=True, help_text='Enable SMS notifications')),
                ('sms_gateway', models.CharField(default='twilio', help_text='SMS gateway provider', max_length=50)),
                ('sms_api_key', models.CharField(blank=True, help_text='Encrypted SMS API key', max_length=255, null=True)),
                ('sms_sender_id', models.CharField(blank=True, help_text='SMS sender ID', max_length=20, null=True)),
                ('email_enabled', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('email_gateway', models.CharField(default='sendgrid', help_text='Email gateway provider', max_length=50)),
                ('email_api_key', models.CharField(blank=True, help_text='Encrypted email API key', max_length=255, null=True)),
                ('email_from', models.EmailField(blank=True, help_text='Sender email address', max_length=254, null=True)),
                ('whatsapp_enabled', models.BooleanField(default=False, help_text='Enable WhatsApp notifications')),
                ('whatsapp_api_key', models.CharField(blank=True, help_text='Encrypted WhatsApp API key', max_length=255, null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp sender number', max_length=20, null=True)),
                ('attendance_notif', models.BooleanField(default=True, help_text='Enable attendance notifications')),
                ('fee_reminder', models.BooleanField(default=True, help_text='Enable fee reminders')),
                ('fee_days', models.CharField(default='7,3,1', help_text='Days before due date to send fee reminders (CSV)', max_length=50)),
                ('notif_settings', models.JSONField(blank=True, help_text='Additional notification configurations (channels, schedules)', null=True)),
                ('college', models.ForeignKey(help_text='Associated college', on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'notification_setting',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('settings', models.JSONField(help_text='System settings (system, email, sms, security, features)')),
                ('college', models.ForeignKey(help_text='Owning college', on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_setting',
            },
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('college', models.ForeignKey(help_text='Associated college', on_delete=django.db.models.deletion.CASCADE, related_name='weekends', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekend',
                'verbose_name_plural': 'Weekends',
                'db_table': 'weekend',
                'ordering': ['day'],
            },
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['code'], name='college_code_00c1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['is_active'], name='college_is_acti_25b463_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['display_order'], name='college_display_e41aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='activity_lo_user_id_ef3d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['college'], name='activity_lo_college_87e6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='activity_lo_timesta_9ed945_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='activity_lo_action_f14761_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['college', 'timestamp'], name='activity_lo_college_0bc63f_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['college'], name='academic_ye_college_8ddefc_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['year'], name='academic_ye_year_5843af_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['is_current'], name='academic_ye_is_curr_cefeb9_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['college', 'is_current'], name='academic_ye_college_13d539_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('college', 'year'), name='unique_college_academic_year'),
        ),
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['college'], name='academic_se_college_3aeae2_idx'),
        ),
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['academic_year'], name='academic_se_academi_681de8_idx'),
        ),
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['is_current'], name='academic_se_is_curr_2197b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('college', 'academic_year', 'semester'), name='unique_college_year_semester'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['college'], name='holiday_college_f2058d_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date'], name='holiday_date_381cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['college', 'date'], name='holiday_college_e60cab_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationsetting',
            index=models.Index(fields=['college'], name='notificatio_college_9080dc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationsetting',
            index=models.Index(fields=['college', 'is_active'], name='notificatio_college_a445ac_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['college'], name='system_sett_college_352a10_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['college', 'is_active'], name='system_sett_college_8076d6_idx'),
        ),
        migrations.AddIndex(
            model_name='weekend',
            index=models.Index(fields=['college'], name='weekend_college_3f767d_idx'),
        ),
        migrations.AddIndex(
            model_name='weekend',
            index=models.Index(fields=['college', 'is_active'], name='weekend_college_27d4a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='weekend',
            constraint=models.UniqueConstraint(fields=('college', 'day'), name='unique_college_weekend_day'),
        ),
    ]
