# Generated by Django 5.2.9 on 2025-12-29 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('role', models.CharField(help_text="Role name (e.g., 'admin', 'teacher', 'student', 'hod')", max_length=50)),
                ('permissions_json', models.JSONField(default=dict, help_text='Permission configuration as JSON')),
                ('college', models.ForeignKey(help_text='Associated college', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permission',
                'ordering': ['college', 'role'],
                'indexes': [models.Index(fields=['college', 'role'], name='permission_college_d263d9_idx'), models.Index(fields=['college'], name='permission_college_83ae48_idx'), models.Index(fields=['role'], name='permission_role_3cac73_idx')],
                'constraints': [models.UniqueConstraint(fields=('college', 'role'), name='unique_college_role_permission')],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('relationship_type', models.CharField(choices=[('teacher_student', 'Teacher-Student'), ('hod_faculty', 'HOD-Faculty'), ('hod_student', 'HOD-Student')], help_text='Type of relationship', max_length=50)),
                ('resource', models.CharField(help_text="Resource this relationship applies to (e.g., 'attendance', 'students')", max_length=50)),
                ('college', models.ForeignKey(help_text='Associated college', on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(help_text='Team leader (teacher, HOD, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='Team member (student, faculty, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Membership',
                'verbose_name_plural': 'Team Memberships',
                'db_table': 'team_membership',
                'ordering': ['college', 'leader'],
                'indexes': [models.Index(fields=['college', 'leader', 'resource'], name='team_member_college_b68bd0_idx'), models.Index(fields=['college', 'member'], name='team_member_college_decd58_idx'), models.Index(fields=['leader'], name='team_member_leader__7f2dee_idx'), models.Index(fields=['member'], name='team_member_member__737bc5_idx')],
                'constraints': [models.UniqueConstraint(fields=('college', 'leader', 'member', 'relationship_type', 'resource'), name='unique_team_membership')],
            },
        ),
    ]
