# Generated by Django 5.2.9 on 2026-01-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_permission_teammembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='relationship_type',
            field=models.CharField(choices=[('teacher_student', 'Teacher-Student'), ('hod_faculty', 'HOD-Faculty'), ('hod_student', 'HOD-Student'), ('hierarchy', 'Hierarchy')], help_text='Type of relationship', max_length=50),
        ),
    ]
