# Generated by Django 5.2.10 on 2026-01-10 06:10

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_teammembership_relationship_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.IntegerField(default=0, help_text="Higher = more authority"),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="Global roles like CEO, central manager",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_roles",
                        to="core.college",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic Role",
                "verbose_name_plural": "Dynamic Roles",
                "db_table": "core_dynamic_role",
            },
        ),
        migrations.CreateModel(
            name="HierarchyPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., students.create", max_length=100, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "app_label",
                    models.CharField(help_text="e.g., students", max_length=50),
                ),
                (
                    "resource",
                    models.CharField(help_text="e.g., student", max_length=50),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                            ("export", "Export"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Academic, Financial, Administrative, etc.",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Hierarchy Permission",
                "verbose_name_plural": "Hierarchy Permissions",
                "db_table": "core_hierarchy_permission",
                "indexes": [
                    models.Index(
                        fields=["app_label", "action"],
                        name="core_hierar_app_lab_a4d46d_idx",
                    ),
                    models.Index(
                        fields=["category"], name="core_hierar_categor_41d6a6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HierarchyUserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hierarchy_role_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.college",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hierarchy_user_assignments",
                        to="core.dynamicrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hierarchy_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hierarchy User Role",
                "verbose_name_plural": "Hierarchy User Roles",
                "db_table": "core_hierarchy_user_role",
            },
        ),
        migrations.CreateModel(
            name="OrganizationNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Node name", max_length=255)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("ceo", "CEO"),
                            ("iti_principal", "ITI Principal"),
                            ("principal_parallel", "Principals Parallel"),
                            ("construction", "Construction And"),
                            ("central_store", "Central Store"),
                            ("spmm_principal", "SPMM Principal"),
                            ("psk", "PSK"),
                            ("principal", "Principal"),
                            ("viceprincipal_super", "Viceprincipal/Super"),
                            ("store_manager", "Store Manager"),
                            ("clerk", "Clerk"),
                            ("accountant", "Accountant"),
                            ("librarian", "Librarian"),
                            ("admission", "Admission and"),
                            ("hostel_incharge", "Hostel Incharge"),
                            ("telecaller", "Telecaller"),
                            ("hostel_rector", "Hostel Rector"),
                            ("mess_canteen", "Mess/Canteen"),
                            ("jr_engineer", "Jr Engineer"),
                            ("viceprincipal", "Viceprincipal"),
                            ("store", "Store"),
                            ("professor", "Professor"),
                            ("associate_professor", "Associate Professor"),
                            ("assistant_professor", "Assistant Professor"),
                            ("lab_assistant", "Lab Assistant"),
                            ("teacher", "Teacher/Trade"),
                            ("hod", "HOD"),
                            ("staff", "Staff"),
                            ("department", "Department"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_nodes",
                        to="core.college",
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.organizationnode",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nodes",
                        to="core.dynamicrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Node",
                "verbose_name_plural": "Organization Nodes",
                "db_table": "core_organization_node",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_delegate",
                    models.BooleanField(
                        default=False, help_text="Can assign this permission to others"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("college", "College"),
                            ("department", "Department"),
                            ("self", "Self Only"),
                        ],
                        default="college",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="core.hierarchypermission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="core.dynamicrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "db_table": "core_role_permission",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "team_type",
                    models.CharField(
                        choices=[
                            ("principal_team", "Principal Team"),
                            ("teacher_team", "Teacher Team"),
                            ("department_team", "Department Team"),
                            ("administrative_team", "Administrative Team"),
                            ("hostel_team", "Hostel Team"),
                            ("store_team", "Store Team"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hierarchy_teams",
                        to="core.college",
                    ),
                ),
                (
                    "lead_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leading_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team",
                        to="core.organizationnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hierarchy Team",
                "verbose_name_plural": "Hierarchy Teams",
                "db_table": "core_hierarchy_team",
            },
        ),
        migrations.CreateModel(
            name="HierarchyTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_in_team",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("deputy", "Deputy"),
                            ("coordinator", "Coordinator"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=50,
                    ),
                ),
                (
                    "auto_assigned",
                    models.BooleanField(
                        default=False, help_text="Was this membership auto-assigned?"
                    ),
                ),
                (
                    "assignment_reason",
                    models.TextField(
                        blank=True, help_text="Reason for auto-assignment"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hierarchy_team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hierarchy Team Member",
                "verbose_name_plural": "Hierarchy Team Members",
                "db_table": "core_hierarchy_team_member",
            },
        ),
        migrations.AddIndex(
            model_name="dynamicrole",
            index=models.Index(
                fields=["is_global", "is_active"], name="core_dynami_is_glob_37c1d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dynamicrole",
            index=models.Index(
                fields=["college", "is_active"], name="core_dynami_college_30fff0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hierarchyuserrole",
            index=models.Index(
                fields=["user", "is_active"], name="core_hierar_user_id_86a657_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hierarchyuserrole",
            index=models.Index(
                fields=["role", "is_active"], name="core_hierar_role_id_bd5f90_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hierarchyuserrole",
            unique_together={("user", "role", "college")},
        ),
        migrations.AddIndex(
            model_name="organizationnode",
            index=models.Index(
                fields=["node_type", "is_active"], name="core_organi_node_ty_6e7a44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationnode",
            index=models.Index(
                fields=["college", "is_active"], name="core_organi_college_483d9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["role", "permission"], name="core_role_p_role_id_da917b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["college", "is_active"], name="core_hierar_college_a976e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["team_type", "is_active"], name="core_hierar_team_ty_dce178_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hierarchyteammember",
            index=models.Index(
                fields=["user", "team"], name="core_hierar_user_id_fc1329_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hierarchyteammember",
            unique_together={("team", "user")},
        ),
    ]
