# Generated by Django 5.2.9 on 2026-01-01 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_permission_teammembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('request_type', models.CharField(choices=[('fee_payment', 'Fee Payment'), ('document_verification', 'Document Verification'), ('leave_request', 'Leave Request'), ('expense_claim', 'Expense Claim'), ('other', 'Other')], help_text='Type of approval request', max_length=50)),
                ('title', models.CharField(help_text='Request title', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Request description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Request priority', max_length=20)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the related object')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Approval status', max_length=20)),
                ('requires_approval_count', models.IntegerField(default=1, help_text='Number of approvals required (for multi-level approval)')),
                ('current_approval_count', models.IntegerField(default=0, help_text='Current number of approvals received')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Submission time')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Review time', null=True)),
                ('deadline', models.DateTimeField(blank=True, help_text='Approval deadline', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the request')),
                ('attachment', models.FileField(blank=True, help_text='Supporting document/attachment', null=True, upload_to='approval_attachments/')),
                ('approvers', models.ManyToManyField(help_text='Users who can approve this request', related_name='approval_requests_to_review', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.college')),
                ('content_type', models.ForeignKey(help_text='Content type of the related object', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='User who made the request', on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'db_table': 'approval_request',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('comment', 'Commented'), ('request_changes', 'Requested Changes')], help_text='Action taken', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Comment/reason for action')),
                ('actioned_at', models.DateTimeField(auto_now_add=True, help_text='Action timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the actor', null=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(help_text='Approval request', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalrequest')),
            ],
            options={
                'verbose_name': 'Approval Action',
                'verbose_name_plural': 'Approval Actions',
                'db_table': 'approval_action',
                'ordering': ['-actioned_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('notification_type', models.CharField(choices=[('approval_request', 'Approval Request'), ('approval_approved', 'Approval Approved'), ('approval_rejected', 'Approval Rejected'), ('payment_received', 'Payment Received'), ('document_uploaded', 'Document Uploaded'), ('general', 'General Notification'), ('system', 'System Notification')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=300)),
                ('message', models.TextField(help_text='Notification message')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Notification priority', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to redirect to when notification is clicked', max_length=500)),
                ('is_read', models.BooleanField(default=False, help_text='Read status')),
                ('read_at', models.DateTimeField(blank=True, help_text='Read timestamp', null=True)),
                ('is_sent', models.BooleanField(default=False, help_text='Send status')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='Sent timestamp')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiry time', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='Notification recipient', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['college', 'status', 'request_type'], name='approval_re_college_e57344_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requester', 'status'], name='approval_re_request_421b04_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='approval_re_content_3a0cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['submitted_at', 'deadline'], name='approval_re_submitt_633063_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['approval_request', 'action'], name='approval_ac_approva_07272a_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['actor', 'actioned_at'], name='approval_ac_actor_i_57b0e1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'sent_at'], name='notificatio_recipie_92e6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'sent_at'], name='notificatio_notific_1c8856_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='notificatio_content_0c2d97_idx'),
        ),
    ]
