# Generated by Django 5.2.9 on 2026-01-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('fee_payment', 'Fee Payment'), ('document_verification', 'Document Verification'), ('leave_request', 'Leave Request'), ('expense_claim', 'Expense Claim'), ('procurement_requirement', 'Procurement Requirement'), ('goods_inspection', 'Goods Inspection'), ('store_indent', 'Store Indent'), ('other', 'Other')], help_text='Type of approval request', max_length=50),
        ),
    ]
