# Generated by Django 5.0.14 on 2025-12-20 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('name', models.CharField(help_text='Leave type', max_length=100)),
                ('code', models.CharField(help_text='Code', max_length=20)),
                ('max_days_per_year', models.IntegerField(help_text='Max days per year')),
                ('is_paid', models.BooleanField(default=True, help_text='Paid leave')),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_type',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('total_days', models.IntegerField(help_text='Total days')),
                ('used_days', models.IntegerField(default=0, help_text='Used days')),
                ('balance_days', models.IntegerField(help_text='Balance days')),
                ('academic_year', models.ForeignKey(help_text='Academic year', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='core.academicyear')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Teacher', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='teachers.teacher')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(help_text='Leave type', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.leavetype')),
            ],
            options={
                'db_table': 'leave_balance',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('from_date', models.DateField(help_text='From date')),
                ('to_date', models.DateField(help_text='To date')),
                ('total_days', models.IntegerField(help_text='Total days')),
                ('reason', models.TextField(help_text='Reason')),
                ('attachment', models.FileField(blank=True, help_text='Attachment', null=True, upload_to='leave_attachments/')),
                ('status', models.CharField(default='pending', help_text='Status', max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True, help_text='Applied date')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Teacher', on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='teachers.teacher')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(help_text='Leave type', on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='hr.leavetype')),
            ],
            options={
                'db_table': 'leave_application',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField(help_text='Year')),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Gross salary', max_digits=10)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, help_text='Total allowances', max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, help_text='Total deductions', max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Net salary', max_digits=10)),
                ('payment_date', models.DateField(blank=True, help_text='Payment date', null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method', max_length=20, null=True)),
                ('status', models.CharField(default='pending', help_text='Status', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Remarks', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Teacher', on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='teachers.teacher')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll',
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('component_name', models.CharField(help_text='Component name', max_length=100)),
                ('component_type', models.CharField(help_text='Type (allowance/deduction)', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount', max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(help_text='Payroll', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hr.payroll')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_item',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('slip_number', models.CharField(help_text='Slip number', max_length=50, unique=True)),
                ('slip_file', models.FileField(blank=True, help_text='Slip PDF', null=True, upload_to='payslips/')),
                ('issue_date', models.DateField(help_text='Issue date')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(help_text='Payroll', on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payroll')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payslip',
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('effective_from', models.DateField(help_text='Effective from')),
                ('effective_to', models.DateField(blank=True, help_text='Effective to', null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Basic salary', max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, help_text='HRA', max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, default=0, help_text='DA', max_digits=10)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, help_text='Other allowances', max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Gross salary', max_digits=10)),
                ('is_current', models.BooleanField(default=True, help_text='Current structure')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Teacher', on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='teachers.teacher')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salary_structure',
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('component_name', models.CharField(help_text='Component name', max_length=100)),
                ('component_type', models.CharField(help_text='Type (allowance/deduction)', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount', max_digits=10)),
                ('is_taxable', models.BooleanField(default=True, help_text='Taxable')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(help_text='Salary structure', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hr.salarystructure')),
            ],
            options={
                'db_table': 'salary_component',
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary_structure',
            field=models.ForeignKey(help_text='Salary structure', on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='hr.salarystructure'),
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('name', models.CharField(help_text='Deduction name', max_length=100)),
                ('code', models.CharField(help_text='Code', max_length=20)),
                ('deduction_type', models.CharField(help_text='Type (fixed/percentage)', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount', max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage', max_digits=5, null=True)),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deduction',
                'indexes': [models.Index(fields=['college', 'code'], name='deduction_college_14fa75_idx'), models.Index(fields=['is_active'], name='deduction_is_acti_918767_idx')],
                'unique_together': {('college', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('status', models.CharField(help_text='Status', max_length=20)),
                ('approval_date', models.DateField(help_text='Approval date')),
                ('remarks', models.TextField(blank=True, help_text='Remarks', null=True)),
                ('application', models.ForeignKey(help_text='Leave application', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='hr.leaveapplication')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Approved by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_approval',
                'indexes': [models.Index(fields=['application', 'approved_by'], name='leave_appro_applica_974197_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['college', 'code'], name='leave_type_college_32165e_idx'),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['college', 'is_active'], name='leave_type_college_cfdfd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('college', 'code')},
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['teacher', 'leave_type', 'academic_year'], name='leave_balan_teacher_c60cdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('teacher', 'leave_type', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['teacher', 'leave_type', 'from_date', 'status'], name='leave_appli_teacher_795b38_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['payroll'], name='payroll_ite_payroll_468115_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['payroll', 'slip_number'], name='payslip_payroll_70996e_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['teacher', 'effective_from', 'is_current'], name='salary_stru_teacher_0c4373_idx'),
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['structure'], name='salary_comp_structu_c7da6f_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['teacher', 'month', 'year'], name='payroll_teacher_2a85aa_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='payroll_status_ac0f6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('teacher', 'month', 'year')},
        ),
    ]
