# Generated by Django 5.2.9 on 2025-12-05 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectassignment',
            name='subject',
            field=models.ForeignKey(help_text='Subject reference', on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academic.subject'),
        ),
    ]
