# Generated by Django 5.0.14 on 2025-12-20 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_alter_subjectassignment_subject'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('title', models.CharField(help_text='Message title', max_length=200)),
                ('message_type', models.CharField(help_text='Type (SMS/Email/WhatsApp)', max_length=20)),
                ('recipient_type', models.CharField(help_text='Recipients type', max_length=20)),
                ('total_recipients', models.IntegerField(default=0, help_text='Total recipients')),
                ('sent_count', models.IntegerField(default=0, help_text='Sent count')),
                ('failed_count', models.IntegerField(default=0, help_text='Failed count')),
                ('status', models.CharField(default='pending', help_text='Status', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Scheduled time', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Sent time', null=True)),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='bulk_messages', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_message',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('title', models.CharField(help_text='Event title', max_length=300)),
                ('description', models.TextField(help_text='Description')),
                ('event_date', models.DateField(help_text='Event date')),
                ('start_time', models.TimeField(help_text='Start time')),
                ('end_time', models.TimeField(help_text='End time')),
                ('venue', models.CharField(blank=True, help_text='Venue', max_length=200, null=True)),
                ('organizer', models.CharField(blank=True, help_text='Organizer', max_length=200, null=True)),
                ('max_participants', models.IntegerField(blank=True, help_text='Max participants', null=True)),
                ('registration_required', models.BooleanField(default=False, help_text='Registration required')),
                ('registration_deadline', models.DateField(blank=True, help_text='Registration deadline', null=True)),
                ('image', models.ImageField(blank=True, help_text='Event image', null=True, upload_to='event_images/')),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('registration_date', models.DateField(help_text='Registration date')),
                ('status', models.CharField(default='registered', help_text='Status', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(help_text='Event', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='communication.event')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_registration',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('message_type', models.CharField(help_text='Type (SMS/Email/WhatsApp)', max_length=20)),
                ('phone_email', models.CharField(help_text='Phone/Email', max_length=200)),
                ('message', models.TextField(help_text='Message content')),
                ('status', models.CharField(default='pending', help_text='Status', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Sent time', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Delivered time', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message', null=True)),
                ('bulk_message', models.ForeignKey(blank=True, help_text='Bulk message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='communication.bulkmessage')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='Recipient', on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_log',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('code', models.CharField(help_text='Template code', max_length=50)),
                ('message_type', models.CharField(help_text='Type (SMS/Email/WhatsApp)', max_length=20)),
                ('content', models.TextField(help_text='Template content')),
                ('variables', models.CharField(blank=True, help_text='Variables (comma-separated)', max_length=500, null=True)),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_template',
            },
        ),
        migrations.AddField(
            model_name='bulkmessage',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_messages', to='communication.messagetemplate'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('title', models.CharField(help_text='Notice title', max_length=300)),
                ('content', models.TextField(help_text='Notice content')),
                ('publish_date', models.DateField(help_text='Publish date')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date', null=True)),
                ('attachment', models.FileField(blank=True, help_text='Attachment', null=True, upload_to='notice_attachments/')),
                ('is_urgent', models.BooleanField(default=False, help_text='Urgent flag')),
                ('is_published', models.BooleanField(default=False, help_text='Published flag')),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='NoticeVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('target_type', models.CharField(help_text='Type (all/class/section)', max_length=20)),
                ('class_obj', models.ForeignKey(blank=True, help_text='Class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_visibilities', to='academic.class')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(help_text='Notice', on_delete=django.db.models.deletion.CASCADE, related_name='visibilities', to='communication.notice')),
                ('section', models.ForeignKey(blank=True, help_text='Section', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_visibilities', to='academic.section')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notice_visibility',
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('name', models.CharField(help_text='Rule name', max_length=100)),
                ('event_type', models.CharField(help_text='Event type', max_length=50)),
                ('channels', models.CharField(help_text='Channels (SMS,Email,WhatsApp)', max_length=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enabled flag')),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to='communication.messagetemplate')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_rule',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('message', models.TextField(help_text='Message content')),
                ('attachment', models.FileField(blank=True, help_text='Attachment', null=True, upload_to='chat_attachments/')),
                ('is_read', models.BooleanField(default=False, help_text='Read flag')),
                ('read_at', models.DateTimeField(blank=True, help_text='Read time', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(help_text='Receiver', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='Sender', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message',
                'indexes': [models.Index(fields=['sender', 'receiver', 'timestamp', 'is_read'], name='chat_messag_sender__c2dd28_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['college', 'event_date'], name='event_college_fc23e8_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'user'], name='event_regis_event_i_65e73e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['bulk_message', 'recipient', 'status'], name='message_log_bulk_me_e1bacb_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['college', 'code'], name='message_tem_college_1740c4_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['is_active'], name='message_tem_is_acti_084c3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('college', 'code')},
        ),
        migrations.AddIndex(
            model_name='bulkmessage',
            index=models.Index(fields=['college', 'status', 'scheduled_at'], name='bulk_messag_college_a47620_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['college', 'publish_date', 'is_published'], name='notice_college_7b6964_idx'),
        ),
        migrations.AddIndex(
            model_name='noticevisibility',
            index=models.Index(fields=['notice', 'class_obj', 'section'], name='notice_visi_notice__ea3a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['college', 'event_type'], name='notificatio_college_471e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['is_active'], name='notificatio_is_acti_6cab93_idx'),
        ),
    ]
