# Generated by Django 5.2.9 on 2026-01-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_add_conversation_and_typing_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_convers_dca7ce_idx',
            old_name='chatmsg_conv_time_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_user1_i_9560f0_idx',
            old_name='conversation_user1_user2_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_last_me_888aec_idx',
            old_name='conversation_last_msg_idx',
        ),
        migrations.RenameIndex(
            model_name='typingindicator',
            new_name='typing_indi_convers_b85432_idx',
            old_name='typing_partner_time_idx',
        ),
    ]
