# Generated by Django 5.2.9 on 2026-01-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_rename_chatmsg_conv_time_idx_chat_messag_convers_dca7ce_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Active status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('notification_type', models.CharField(choices=[('message', 'New Message'), ('notice', 'Notice Posted'), ('event', 'Event Created'), ('event_reminder', 'Event Reminder'), ('registration', 'Registration Update'), ('assignment', 'Assignment Posted'), ('grade', 'Grade Posted'), ('announcement', 'Announcement'), ('system', 'System Notification')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('link', models.CharField(blank=True, help_text='Link to related resource', max_length=500, null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Related model type', max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, help_text='Related object ID', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Read flag')),
                ('read_at', models.DateTimeField(blank=True, help_text='Read timestamp', null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name/class', max_length=50, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Notification priority', max_length=20)),
                ('recipient', models.ForeignKey(help_text='Notification recipient', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'in_app_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient', '-created_at'], name='in_app_noti_recipie_8c123f_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='in_app_noti_recipie_9d456a_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['notification_type', 'recipient'], name='in_app_noti_notific_7e234b_idx'),
        ),
    ]
