# Generated by Django 5.2.9 on 2025-12-22 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_alter_subjectassignment_subject'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('date', models.DateField(help_text='Attendance date')),
                ('status', models.CharField(help_text='Status (present/absent/late/half_day)', max_length=20)),
                ('check_in_time', models.TimeField(blank=True, help_text='Check-in time', null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='Check-out time', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Remarks', null=True)),
                ('class_obj', models.ForeignKey(help_text='Class reference', on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='academic.class')),
                ('marked_by', models.ForeignKey(blank=True, help_text='Marked by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_student_attendance', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(help_text='Section reference', on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='academic.section')),
                ('student', models.ForeignKey(help_text='Student reference', on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendance',
                'db_table': 'student_attendance',
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SubjectAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('date', models.DateField(help_text='Attendance date')),
                ('status', models.CharField(help_text='Status (present/absent/late)', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Remarks', null=True)),
                ('student', models.ForeignKey(help_text='Student reference', on_delete=django.db.models.deletion.CASCADE, related_name='subject_attendance', to='students.student')),
                ('subject_assignment', models.ForeignKey(help_text='Subject assignment', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.subjectassignment')),
                ('period', models.ForeignKey(blank=True, help_text='Class period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attendance', to='academic.classtime')),
                ('marked_by', models.ForeignKey(blank=True, help_text='Marked by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_subject_attendance', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Subject Attendance',
                'verbose_name_plural': 'Subject Attendance',
                'db_table': 'subject_attendance',
                'unique_together': {('student', 'subject_assignment', 'date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('date', models.DateField(help_text='Attendance date')),
                ('status', models.CharField(help_text='Status (present/absent/on_leave/half_day)', max_length=20)),
                ('check_in_time', models.TimeField(blank=True, help_text='Check-in time', null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='Check-out time', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Remarks', null=True)),
                ('marked_by', models.ForeignKey(blank=True, help_text='Marked by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_staff_attendance', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Teacher reference', on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Staff Attendance',
                'verbose_name_plural': 'Staff Attendance',
                'db_table': 'staff_attendance',
                'unique_together': {('teacher', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('recipient_type', models.CharField(help_text='Recipient type (parent/student/admin)', max_length=20)),
                ('notification_type', models.CharField(help_text='Notification type (sms/email/whatsapp/push)', max_length=20)),
                ('status', models.CharField(default='pending', help_text='Status (pending/sent/delivered/failed)', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Sent timestamp', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Delivered timestamp', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message', null=True)),
                ('message', models.TextField(help_text='Message content')),
                ('attendance', models.ForeignKey(help_text='Attendance reference', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.studentattendance')),
                ('recipient', models.ForeignKey(help_text='Recipient', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Notification',
                'verbose_name_plural': 'Attendance Notifications',
                'db_table': 'attendance_notification',
            },
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'date'], name='student_att_student_7f9c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date', 'class_obj', 'section'], name='student_att_date_cla_64de45_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['class_obj', 'section'], name='student_att_class_o_f3cbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectattendance',
            index=models.Index(fields=['student', 'subject_assignment', 'date'], name='subject_att_student_e38d96_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectattendance',
            index=models.Index(fields=['date', 'period'], name='subject_att_date_per_d2f64a_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['teacher', 'date'], name='staff_att_teacher_22ccb6_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['date'], name='staff_att_date_557fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancenotification',
            index=models.Index(fields=['attendance', 'recipient'], name='attendance_attendan_51c8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancenotification',
            index=models.Index(fields=['status'], name='attendance_status_8bd4db_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancenotification',
            index=models.Index(fields=['notification_type'], name='attendance_notifica_4adf51_idx'),
        ),
    ]
