# Generated by Django 5.0.14 on 2025-12-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancenotification',
            new_name='attendance__attenda_9a811d_idx',
            old_name='attendance_attendan_51c8d9_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancenotification',
            new_name='attendance__status_01d310_idx',
            old_name='attendance_status_8bd4db_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancenotification',
            new_name='attendance__notific_b339c1_idx',
            old_name='attendance_notifica_4adf51_idx',
        ),
        migrations.RenameIndex(
            model_name='staffattendance',
            new_name='staff_atten_teacher_1d7f64_idx',
            old_name='staff_att_teacher_22ccb6_idx',
        ),
        migrations.RenameIndex(
            model_name='staffattendance',
            new_name='staff_atten_date_5cc967_idx',
            old_name='staff_att_date_557fd4_idx',
        ),
        migrations.RenameIndex(
            model_name='studentattendance',
            new_name='student_att_student_39038c_idx',
            old_name='student_att_student_7f9c8f_idx',
        ),
        migrations.RenameIndex(
            model_name='studentattendance',
            new_name='student_att_date_b5162d_idx',
            old_name='student_att_date_cla_64de45_idx',
        ),
        migrations.RenameIndex(
            model_name='studentattendance',
            new_name='student_att_class_o_c63086_idx',
            old_name='student_att_class_o_f3cbe1_idx',
        ),
        migrations.RenameIndex(
            model_name='subjectattendance',
            new_name='subject_att_student_2d344d_idx',
            old_name='subject_att_student_e38d96_idx',
        ),
        migrations.RenameIndex(
            model_name='subjectattendance',
            new_name='subject_att_date_3208af_idx',
            old_name='subject_att_date_per_d2f64a_idx',
        ),
    ]
