# Generated by Django 5.2.9 on 2025-12-05 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_alter_subjectassignment_subject'),
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('title', models.CharField(help_text='Assignment title', max_length=300)),
                ('description', models.TextField(help_text='Description')),
                ('assignment_file', models.FileField(blank=True, help_text='Assignment file', null=True, upload_to='assignments/')),
                ('assigned_date', models.DateField(auto_now_add=True, help_text='Assigned date')),
                ('due_date', models.DateField(help_text='Due date')),
                ('max_marks', models.IntegerField(help_text='Maximum marks')),
                ('allow_late_submission', models.BooleanField(default=False, help_text='Allow late submission')),
                ('late_submission_penalty', models.IntegerField(default=0, help_text='Penalty percentage')),
                ('class_obj', models.ForeignKey(help_text='Class reference', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.class')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, help_text='Section reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academic.section')),
                ('subject', models.ForeignKey(help_text='Subject reference', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.subject')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('title', models.CharField(help_text='Homework title', max_length=300)),
                ('description', models.TextField(help_text='Description')),
                ('attachment', models.FileField(blank=True, help_text='Attachment', null=True, upload_to='homework/')),
                ('assigned_date', models.DateField(auto_now_add=True, help_text='Assigned date')),
                ('due_date', models.DateField(help_text='Due date')),
                ('class_obj', models.ForeignKey(help_text='Class reference', on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='academic.class')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, help_text='Section reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='academic.section')),
                ('subject', models.ForeignKey(help_text='Subject reference', on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='academic.subject')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homework',
                'db_table': 'homework',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('employee_id', models.CharField(db_index=True, help_text='Employee ID', max_length=50, unique=True)),
                ('joining_date', models.DateField(help_text='Joining date')),
                ('first_name', models.CharField(help_text='First name', max_length=100)),
                ('middle_name', models.CharField(blank=True, help_text='Middle name', max_length=100, null=True)),
                ('last_name', models.CharField(help_text='Last name', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('gender', models.CharField(help_text='Gender', max_length=10)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('phone', models.CharField(help_text='Phone', max_length=20)),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate phone', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Address', null=True)),
                ('photo', models.ImageField(blank=True, help_text='Photo', null=True, upload_to='teacher_photos/')),
                ('specialization', models.CharField(blank=True, help_text='Main specialization', max_length=200, null=True)),
                ('qualifications', models.JSONField(blank=True, default=list, help_text='List of degrees (Name, Year, University)', null=True)),
                ('experience_details', models.JSONField(blank=True, default=list, help_text='List of past jobs (Organization, Role, Dates)', null=True)),
                ('custom_attributes', models.JSONField(blank=True, default=dict, help_text='Custom key-value pairs', null=True)),
                ('resignation_date', models.DateField(blank=True, help_text='Resignation date', null=True)),
                ('college', models.ForeignKey(help_text='College reference', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.college')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, help_text='Faculty/Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academic.faculty')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User account', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active (soft delete)')),
                ('title', models.CharField(help_text='Material title', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('content_type', models.CharField(help_text='Content type (pdf/video/document/link)', max_length=20)),
                ('file', models.FileField(blank=True, help_text='File upload', null=True, upload_to='study_materials/')),
                ('external_url', models.URLField(blank=True, help_text='External URL', null=True)),
                ('topic', models.CharField(blank=True, help_text='Topic', max_length=200, null=True)),
                ('tags', models.CharField(blank=True, help_text='Tags (comma-separated)', max_length=500, null=True)),
                ('upload_date', models.DateField(auto_now_add=True, help_text='Upload date')),
                ('view_count', models.IntegerField(default=0, help_text='View count')),
                ('class_obj', models.ForeignKey(help_text='Class reference', on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='academic.class')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, help_text='Section reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_materials', to='academic.section')),
                ('subject', models.ForeignKey(help_text='Subject reference', on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='academic.subject')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Teacher reference', on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'db_table': 'study_material',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('status', models.CharField(default='pending', help_text='Status (pending/completed/checked)', max_length=20)),
                ('completion_date', models.DateField(blank=True, help_text='Completion date', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Remarks', null=True)),
                ('checked_date', models.DateField(blank=True, help_text='Checked date', null=True)),
                ('homework', models.ForeignKey(help_text='Homework reference', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teachers.homework')),
                ('student', models.ForeignKey(help_text='Student reference', on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='students.student')),
                ('checked_by', models.ForeignKey(blank=True, help_text='Checked by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_homework', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Homework Submission',
                'verbose_name_plural': 'Homework Submissions',
                'db_table': 'homework_submission',
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher reference', on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='teachers.teacher'),
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('submission_date', models.DateTimeField(auto_now_add=True, help_text='Submission date')),
                ('submission_file', models.FileField(blank=True, help_text='Submission file', null=True, upload_to='assignment_submissions/')),
                ('submission_text', models.TextField(blank=True, help_text='Submission text', null=True)),
                ('status', models.CharField(default='submitted', help_text='Status (pending/submitted/graded)', max_length=20)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Marks obtained', max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback', null=True)),
                ('graded_date', models.DateTimeField(blank=True, help_text='Graded date', null=True)),
                ('is_late', models.BooleanField(default=False, help_text='Late submission flag')),
                ('assignment', models.ForeignKey(help_text='Assignment reference', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teachers.assignment')),
                ('student', models.ForeignKey(help_text='Student reference', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='students.student')),
                ('graded_by', models.ForeignKey(blank=True, help_text='Graded by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'db_table': 'assignment_submission',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher reference', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacher'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['employee_id'], name='teacher_employe_9b5969_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['college'], name='teacher_college_71a625_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('college', 'employee_id')},
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['teacher', 'subject', 'class_obj', 'upload_date'], name='study_mater_teacher_e97e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['homework', 'student'], name='homework_su_homewor_7bf898_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['status'], name='homework_su_status_20e555_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='homeworksubmission',
            unique_together={('homework', 'student')},
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['teacher', 'subject', 'class_obj', 'due_date'], name='homework_teacher_3be093_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'student'], name='assignment__assignm_1e32ac_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['status'], name='assignment__status_a5812f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['teacher', 'subject', 'class_obj', 'due_date'], name='assignment_teacher_c2e56e_idx'),
        ),
    ]
