# Generated by Django 5.0.14 on 2025-12-22 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admitcard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examattendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examschedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marksgrade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marksheet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marksregister',
            options={},
        ),
        migrations.AlterModelOptions(
            name='progresscard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentmarks',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tabulationsheet',
            options={},
        ),
        migrations.RenameIndex(
            model_name='admitcard',
            new_name='admit_card_student_cbfe6a_idx',
            old_name='admit_card_student__83aee5_idx',
        ),
        migrations.RenameIndex(
            model_name='exam',
            new_name='exam_college_c96912_idx',
            old_name='exam_college_exam_ty_a248a7_idx',
        ),
        migrations.RenameIndex(
            model_name='examattendance',
            new_name='exam_attend_exam_sc_b8be17_idx',
            old_name='exam_attend_exam_sc_7ca7c5_idx',
        ),
        migrations.RenameIndex(
            model_name='examresult',
            new_name='exam_result_student_28f5dd_idx',
            old_name='exam_resul_student__c66310_idx',
        ),
        migrations.RenameIndex(
            model_name='examschedule',
            new_name='exam_schedu_exam_id_e1dfa8_idx',
            old_name='exam_sched_exam_id__848fc1_idx',
        ),
        migrations.RenameIndex(
            model_name='examtype',
            new_name='exam_type_college_e7638c_idx',
            old_name='exam_type_college_86f1a3_idx',
        ),
        migrations.RenameIndex(
            model_name='marksgrade',
            new_name='marks_grade_college_8e6500_idx',
            old_name='marks_grad_college_4ee676_idx',
        ),
        migrations.RenameIndex(
            model_name='marksheet',
            new_name='mark_sheet_student_33d0d1_idx',
            old_name='mark_sheet_student__c14076_idx',
        ),
        migrations.RenameIndex(
            model_name='marksregister',
            new_name='marks_regis_exam_id_ad257f_idx',
            old_name='marks_regi_exam_id__e4301f_idx',
        ),
        migrations.RenameIndex(
            model_name='progresscard',
            new_name='progress_ca_student_8416cb_idx',
            old_name='progress_c_student__5970b0_idx',
        ),
        migrations.RenameIndex(
            model_name='studentmarks',
            new_name='student_mar_registe_05d879_idx',
            old_name='student_ma_register_57ba46_idx',
        ),
        migrations.RenameIndex(
            model_name='tabulationsheet',
            new_name='tabulation__exam_id_891d8b_idx',
            old_name='tabulation_exam_id__f28dfd_idx',
        ),
        migrations.AlterField(
            model_name='exam',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.academicsession'),
        ),
    ]
