# Generated by Django 5.0.14 on 2025-12-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='onlineexam',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionbank',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentexamattempt',
            options={},
        ),
        migrations.RenameIndex(
            model_name='examquestion',
            new_name='exam_questi_exam_id_246891_idx',
            old_name='exam_quest_exam_id__a803aa_idx',
        ),
        migrations.RenameIndex(
            model_name='onlineexam',
            new_name='online_exam_college_456005_idx',
            old_name='online_exa_college_537a0e_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='question_bank_id_a06d61_idx',
            old_name='question_b_bank_id__648c2e_idx',
        ),
        migrations.RenameIndex(
            model_name='questionbank',
            new_name='question_ba_college_7fc361_idx',
            old_name='question_b_college_3d4857_idx',
        ),
        migrations.RenameIndex(
            model_name='questionoption',
            new_name='question_op_questio_f6520b_idx',
            old_name='question_o_question_7d6cb1_idx',
        ),
        migrations.RenameIndex(
            model_name='studentanswer',
            new_name='student_ans_attempt_a1a9ed_idx',
            old_name='student_an_attempt__2f2e15_idx',
        ),
        migrations.RenameIndex(
            model_name='studentexamattempt',
            new_name='student_exa_exam_id_ec9d0a_idx',
            old_name='student_ex_exam_id__4c8597_idx',
        ),
    ]
